name: CI
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go version
      - run: go build ./cmd/shorty
      - run: go test ./...
